baseURL = "https://felixruntime.github.io/"
languageCode = "en"
title = "felixruntime"

[taxonomies]
  tag = "tags"
  series = "series"

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
