colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

[homepage]
  layout = "profile"
  homepageImage = "img/author.jpg"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/blog"
  cardView = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showBreadcrumbs = true

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = false
