colorScheme = "neural"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

[homepage]
  layout = "hero"
  # homepageImage = "img/author.jpg"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/blog"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showBreadcrumbs = true
  showTaxonomies = true
  showWordCount = false
  showEdit = false
  showPagination = true

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = true
  cardView = true

[taxonomy]
  showTermCount = true
  cardView = false

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
